/**
 * 门店客户列表模拟数据
 * 所有数据均为虚构，不包含真实客户、门店、员工或账号信息
 */

export interface CustomerRecord {
  key: string;
  name: string;
  firstAssignTime: string;
  lastAssignTime: string;
  isVisited: string;
  isDeal: string;
  appointmentTime: string;
  actualVisitStatus: string;
  actualDealStatus: string;
  id: string;
  userId: string;
  wechatId: string;
  phone: string;
  retainStore: string;
  retainStoreRemark: string;
  gender: string;
  age: number | string;
  source: string;
  customerType: string;
  isAssigned: string;
  latestFollower: string;
  sharer: string;
  visitCount: number;
  visitCount7d: number;
  visitCount30d: number;
  interviewCount: number;
  interviewCount7d: number;
  interviewCount30d: number;
  conversionDays: number | string;
  dealCycleDays: number | string;
  latestEditor: string;
  remark: string;
  inviteEmployeeId: string;
  inviteEmployeeName: string;
  groundPromotionQuestionnaire: string;
  answer: string;
  questionnaireSubmitTime: string;
  appointmentStore: string;
  isGiftTrialClass: string;
  trialClassGetTime: string;
  contractNo: string;
  isAppointed: string;
  trialClassStatus: string;
  trialClassEndTime: string;
  userTags: string;
  trialClassPayAmount: number | string;
  trialClassConsultant: string;
  isRegistered: string;
  repeatRetainCount: number | string;
  latestRetainTime: string;
  invalidCustomerStatus: string;
  createTime: string;
}

const rawCustomers: CustomerRecord[] = [
  {
    key: '1',
    name: '张三',
    firstAssignTime: '2026-07-21 14:30:00',
    lastAssignTime: '2026-07-22 09:15:00',
    isVisited: '已到店',
    isDeal: '未成交',
    appointmentTime: '2026-07-25 15:00:00',
    actualVisitStatus: '--',
    actualDealStatus: '--',
    id: 'SC001',
    userId: 'UID1001',
    wechatId: 'wx_zhangsan_01',
    phone: '139****4822',
    retainStore: '示例旗舰店',
    retainStoreRemark: '--',
    gender: '男',
    age: 28,
    source: '地推活动',
    customerType: '新客',
    isAssigned: '已分配',
    latestFollower: '王经理',
    sharer: '--',
    visitCount: 3,
    visitCount7d: 1,
    visitCount30d: 3,
    interviewCount: 2,
    interviewCount7d: 0,
    interviewCount30d: 1,
    conversionDays: 15,
    dealCycleDays: '--',
    latestEditor: '王经理',
    remark: '--',
    inviteEmployeeId: 'EMP001',
    inviteEmployeeName: '李员工',
    groundPromotionQuestionnaire: '--',
    answer: '--',
    questionnaireSubmitTime: '0000-00-00 00:00:00',
    appointmentStore: '示例旗舰店',
    isGiftTrialClass: '是',
    trialClassGetTime: '2026-07-20 10:00:00',
    contractNo: '--',
    isAppointed: '是',
    trialClassStatus: '已下课',
    trialClassEndTime: '2026-07-22 17:00:00',
    userTags: '意向客户',
    trialClassPayAmount: 199,
    trialClassConsultant: '张顾问',
    isRegistered: '是',
    repeatRetainCount: 1,
    latestRetainTime: '2026-07-21 14:30:00',
    invalidCustomerStatus: '--',
    createTime: '2026-07-15 08:00:00',
  },
  {
    key: '2',
    name: '李四',
    firstAssignTime: '2026-07-20 10:00:00',
    lastAssignTime: '2026-07-21 16:45:00',
    isVisited: '未到店',
    isDeal: '未成交',
    appointmentTime: '2026-07-28 10:30:00',
    actualVisitStatus: '--',
    actualDealStatus: '--',
    id: 'SC002',
    userId: 'UID1002',
    wechatId: 'wx_lisi_02',
    phone: '138****5731',
    retainStore: '示例南山店',
    retainStoreRemark: '对课程有咨询需求',
    gender: '女',
    age: 35,
    source: '线上广告',
    customerType: '老客',
    isAssigned: '已分配',
    latestFollower: '赵主管',
    sharer: '陈员工',
    visitCount: 5,
    visitCount7d: 2,
    visitCount30d: 4,
    interviewCount: 3,
    interviewCount7d: 1,
    interviewCount30d: 3,
    conversionDays: 8,
    dealCycleDays: 22,
    latestEditor: '赵主管',
    remark: '已预约体验课',
    inviteEmployeeId: 'EMP002',
    inviteEmployeeName: '陈员工',
    groundPromotionQuestionnaire: '体验课意向问卷',
    answer: '已提交',
    questionnaireSubmitTime: '2026-07-19 14:00:00',
    appointmentStore: '示例南山店',
    isGiftTrialClass: '否',
    trialClassGetTime: '-',
    contractNo: '--',
    isAppointed: '否',
    trialClassStatus: '--',
    trialClassEndTime: '0000-00-00 00:00:00',
    userTags: '高意向',
    trialClassPayAmount: '--',
    trialClassConsultant: '--',
    isRegistered: '否',
    repeatRetainCount: 0,
    latestRetainTime: '0000-00-00 00:00:00',
    invalidCustomerStatus: '--',
    createTime: '2026-07-14 09:00:00',
  },
  {
    key: '3',
    name: '王五',
    firstAssignTime: '2026-07-19 08:30:00',
    lastAssignTime: '2026-07-22 08:00:00',
    isVisited: '已到店',
    isDeal: '--',
    appointmentTime: '2026-07-22 14:00:00',
    actualVisitStatus: '--',
    actualDealStatus: '--',
    id: 'SC003',
    userId: 'UID1003',
    wechatId: 'wx_wangwu_03',
    phone: '137****2048',
    retainStore: '示例旗舰店',
    retainStoreRemark: '--',
    gender: '男',
    age: 42,
    source: '朋友推荐',
    customerType: '新客',
    isAssigned: '未分配',
    latestFollower: '--',
    sharer: '--',
    visitCount: 0,
    visitCount7d: 0,
    visitCount30d: 0,
    interviewCount: 0,
    interviewCount7d: 0,
    interviewCount30d: 0,
    conversionDays: '--',
    dealCycleDays: '--',
    latestEditor: '系统',
    remark: '--',
    inviteEmployeeId: '--',
    inviteEmployeeName: '--',
    groundPromotionQuestionnaire: '--',
    answer: '--',
    questionnaireSubmitTime: '0000-00-00 00:00:00',
    appointmentStore: '示例旗舰店',
    isGiftTrialClass: '否',
    trialClassGetTime: '-',
    contractNo: '--',
    isAppointed: '是',
    trialClassStatus: '--',
    trialClassEndTime: '0000-00-00 00:00:00',
    userTags: '--',
    trialClassPayAmount: '--',
    trialClassConsultant: '--',
    isRegistered: '否',
    repeatRetainCount: 0,
    latestRetainTime: '0000-00-00 00:00:00',
    invalidCustomerStatus: '--',
    createTime: '2026-07-13 11:00:00',
  },
  {
    key: '4',
    name: '刘洋',
    firstAssignTime: '2026-07-18 13:00:00',
    lastAssignTime: '2026-07-20 10:30:00',
    isVisited: '未到店',
    isDeal: '未成交',
    appointmentTime: '-',
    actualVisitStatus: '--',
    actualDealStatus: '--',
    id: 'SC004',
    userId: 'UID1004',
    wechatId: 'wx_liuyang_04',
    phone: '136****7193',
    retainStore: '示例福田店',
    retainStoreRemark: '--',
    gender: '女',
    age: 25,
    source: '地推活动',
    customerType: '新客',
    isAssigned: '已分配',
    latestFollower: '张主管',
    sharer: '--',
    visitCount: 1,
    visitCount7d: 0,
    visitCount30d: 1,
    interviewCount: 1,
    interviewCount7d: 0,
    interviewCount30d: 1,
    conversionDays: '--',
    dealCycleDays: '--',
    latestEditor: '张主管',
    remark: '--',
    inviteEmployeeId: 'EMP003',
    inviteEmployeeName: '张员工',
    groundPromotionQuestionnaire: '--',
    answer: '--',
    questionnaireSubmitTime: '0000-00-00 00:00:00',
    appointmentStore: '--',
    isGiftTrialClass: '否',
    trialClassGetTime: '-',
    contractNo: '--',
    isAppointed: '否',
    trialClassStatus: '--',
    trialClassEndTime: '0000-00-00 00:00:00',
    userTags: '--',
    trialClassPayAmount: '--',
    trialClassConsultant: '--',
    isRegistered: '是',
    repeatRetainCount: 2,
    latestRetainTime: '2026-07-18 13:00:00',
    invalidCustomerStatus: '--',
    createTime: '2026-07-12 16:00:00',
  },
  {
    key: '5',
    name: '陈晨',
    firstAssignTime: '2026-07-17 09:00:00',
    lastAssignTime: '2026-07-21 11:00:00',
    isVisited: '已到店',
    isDeal: '未成交',
    appointmentTime: '2026-07-30 09:00:00',
    actualVisitStatus: '--',
    actualDealStatus: '--',
    id: 'SC005',
    userId: 'UID1005',
    wechatId: 'wx_chenchen_05',
    phone: '135****3507',
    retainStore: '示例宝安店',
    retainStoreRemark: '关注儿童课程',
    gender: '女',
    age: 33,
    source: '线上广告',
    customerType: '老客',
    isAssigned: '已分配',
    latestFollower: '刘经理',
    sharer: '周员工',
    visitCount: 8,
    visitCount7d: 3,
    visitCount30d: 6,
    interviewCount: 4,
    interviewCount7d: 2,
    interviewCount30d: 4,
    conversionDays: 30,
    dealCycleDays: 45,
    latestEditor: '刘经理',
    remark: '正在跟进',
    inviteEmployeeId: 'EMP004',
    inviteEmployeeName: '周员工',
    groundPromotionQuestionnaire: '课程意向表',
    answer: '已填写',
    questionnaireSubmitTime: '2026-07-16 10:30:00',
    appointmentStore: '示例宝安店',
    isGiftTrialClass: '是',
    trialClassGetTime: '2026-07-17 14:00:00',
    contractNo: 'HT2026001',
    isAppointed: '是',
    trialClassStatus: '已下课',
    trialClassEndTime: '2026-07-20 16:00:00',
    userTags: '高意向,课程',
    trialClassPayAmount: 299,
    trialClassConsultant: '李顾问',
    isRegistered: '是',
    repeatRetainCount: 3,
    latestRetainTime: '2026-07-17 09:00:00',
    invalidCustomerStatus: '--',
    createTime: '2026-07-10 08:30:00',
  },
  {
    key: '6',
    name: '赵敏',
    firstAssignTime: '2026-07-16 15:00:00',
    lastAssignTime: '2026-07-19 14:00:00',
    isVisited: '--',
    isDeal: '--',
    appointmentTime: '2026-08-01 11:00:00',
    actualVisitStatus: '--',
    actualDealStatus: '--',
    id: 'SC006',
    userId: 'UID1006',
    wechatId: 'wx_zhaomin_06',
    phone: '134****6284',
    retainStore: '示例罗湖店',
    retainStoreRemark: '--',
    gender: '女',
    age: 29,
    source: '商圈引流',
    customerType: '新客',
    isAssigned: '已分配',
    latestFollower: '孙主管',
    sharer: '--',
    visitCount: 2,
    visitCount7d: 1,
    visitCount30d: 2,
    interviewCount: 0,
    interviewCount7d: 0,
    interviewCount30d: 0,
    conversionDays: '--',
    dealCycleDays: '--',
    latestEditor: '孙主管',
    remark: '--',
    inviteEmployeeId: 'EMP005',
    inviteEmployeeName: '钱员工',
    groundPromotionQuestionnaire: '--',
    answer: '--',
    questionnaireSubmitTime: '0000-00-00 00:00:00',
    appointmentStore: '示例罗湖店',
    isGiftTrialClass: '否',
    trialClassGetTime: '-',
    contractNo: '--',
    isAppointed: '是',
    trialClassStatus: '--',
    trialClassEndTime: '0000-00-00 00:00:00',
    userTags: '新客户',
    trialClassPayAmount: '--',
    trialClassConsultant: '--',
    isRegistered: '否',
    repeatRetainCount: 0,
    latestRetainTime: '0000-00-00 00:00:00',
    invalidCustomerStatus: '--',
    createTime: '2026-07-09 13:00:00',
  },
  {
    key: '7',
    name: '周杰',
    firstAssignTime: '2026-07-15 11:00:00',
    lastAssignTime: '2026-07-22 07:30:00',
    isVisited: '已到店',
    isDeal: '未成交',
    appointmentTime: '2026-07-24 16:30:00',
    actualVisitStatus: '--',
    actualDealStatus: '--',
    id: 'SC007',
    userId: 'UID1007',
    wechatId: 'wx_zhoujie_07',
    phone: '133****9815',
    retainStore: '示例旗舰店',
    retainStoreRemark: '会员推荐',
    gender: '男',
    age: 38,
    source: '会员推荐',
    customerType: '老客',
    isAssigned: '已分配',
    latestFollower: '王经理',
    sharer: '--',
    visitCount: 12,
    visitCount7d: 4,
    visitCount30d: 10,
    interviewCount: 6,
    interviewCount7d: 2,
    interviewCount30d: 5,
    conversionDays: 20,
    dealCycleDays: 60,
    latestEditor: '王经理',
    remark: '老客户推荐',
    inviteEmployeeId: 'EMP001',
    inviteEmployeeName: '李员工',
    groundPromotionQuestionnaire: '--',
    answer: '--',
    questionnaireSubmitTime: '0000-00-00 00:00:00',
    appointmentStore: '示例旗舰店',
    isGiftTrialClass: '是',
    trialClassGetTime: '2026-07-16 09:00:00',
    contractNo: '--',
    isAppointed: '是',
    trialClassStatus: '已下课',
    trialClassEndTime: '2026-07-19 18:00:00',
    userTags: 'VIP意向',
    trialClassPayAmount: 399,
    trialClassConsultant: '王顾问',
    isRegistered: '是',
    repeatRetainCount: 5,
    latestRetainTime: '2026-07-15 11:00:00',
    invalidCustomerStatus: '--',
    createTime: '2026-07-08 10:00:00',
  },
  {
    key: '8',
    name: '吴芳',
    firstAssignTime: '2026-07-14 10:30:00',
    lastAssignTime: '2026-07-18 09:00:00',
    isVisited: '未到店',
    isDeal: '--',
    appointmentTime: '-',
    actualVisitStatus: '--',
    actualDealStatus: '--',
    id: 'SC008',
    userId: 'UID1008',
    wechatId: 'wx_wufang_08',
    phone: '132****4762',
    retainStore: '示例南山店',
    retainStoreRemark: '--',
    gender: '女',
    age: 31,
    source: '线上广告',
    customerType: '新客',
    isAssigned: '已分配',
    latestFollower: '赵主管',
    sharer: '--',
    visitCount: 0,
    visitCount7d: 0,
    visitCount30d: 0,
    interviewCount: 0,
    interviewCount7d: 0,
    interviewCount30d: 0,
    conversionDays: '--',
    dealCycleDays: '--',
    latestEditor: '赵主管',
    remark: '待跟进',
    inviteEmployeeId: 'EMP002',
    inviteEmployeeName: '陈员工',
    groundPromotionQuestionnaire: '--',
    answer: '--',
    questionnaireSubmitTime: '0000-00-00 00:00:00',
    appointmentStore: '--',
    isGiftTrialClass: '否',
    trialClassGetTime: '-',
    contractNo: '--',
    isAppointed: '否',
    trialClassStatus: '--',
    trialClassEndTime: '0000-00-00 00:00:00',
    userTags: '--',
    trialClassPayAmount: '--',
    trialClassConsultant: '--',
    isRegistered: '否',
    repeatRetainCount: 0,
    latestRetainTime: '0000-00-00 00:00:00',
    invalidCustomerStatus: '--',
    createTime: '2026-07-07 14:00:00',
  },
  {
    key: '9',
    name: '郑浩',
    firstAssignTime: '2026-07-13 16:00:00',
    lastAssignTime: '2026-07-20 15:30:00',
    isVisited: '已到店',
    isDeal: '未成交',
    appointmentTime: '2026-07-26 10:00:00',
    actualVisitStatus: '--',
    actualDealStatus: '--',
    id: 'SC009',
    userId: 'UID1009',
    wechatId: 'wx_zhenghao_09',
    phone: '131****7903',
    retainStore: '示例福田店',
    retainStoreRemark: '--',
    gender: '男',
    age: 45,
    source: '商圈引流',
    customerType: '新客',
    isAssigned: '已分配',
    latestFollower: '张主管',
    sharer: '--',
    visitCount: 3,
    visitCount7d: 1,
    visitCount30d: 3,
    interviewCount: 1,
    interviewCount7d: 0,
    interviewCount30d: 1,
    conversionDays: 10,
    dealCycleDays: '--',
    latestEditor: '张主管',
    remark: '--',
    inviteEmployeeId: 'EMP003',
    inviteEmployeeName: '张员工',
    groundPromotionQuestionnaire: '消费意向问卷',
    answer: '已提交',
    questionnaireSubmitTime: '2026-07-12 15:00:00',
    appointmentStore: '示例福田店',
    isGiftTrialClass: '否',
    trialClassGetTime: '-',
    contractNo: '--',
    isAppointed: '是',
    trialClassStatus: '--',
    trialClassEndTime: '0000-00-00 00:00:00',
    userTags: '--',
    trialClassPayAmount: '--',
    trialClassConsultant: '--',
    isRegistered: '是',
    repeatRetainCount: 1,
    latestRetainTime: '2026-07-13 16:00:00',
    invalidCustomerStatus: '--',
    createTime: '2026-07-06 09:30:00',
  },
  {
    key: '10',
    name: '孙丽',
    firstAssignTime: '2026-07-12 08:00:00',
    lastAssignTime: '2026-07-19 17:00:00',
    isVisited: '未到店',
    isDeal: '--',
    appointmentTime: '2026-08-05 14:30:00',
    actualVisitStatus: '--',
    actualDealStatus: '--',
    id: 'SC010',
    userId: 'UID1010',
    wechatId: 'wx_sunli_10',
    phone: '130****8537',
    retainStore: '示例宝安店',
    retainStoreRemark: '对体验课感兴趣',
    gender: '女',
    age: 27,
    source: '地推活动',
    customerType: '新客',
    isAssigned: '已分配',
    latestFollower: '刘经理',
    sharer: '--',
    visitCount: 1,
    visitCount7d: 0,
    visitCount30d: 1,
    interviewCount: 0,
    interviewCount7d: 0,
    interviewCount30d: 0,
    conversionDays: '--',
    dealCycleDays: '--',
    latestEditor: '刘经理',
    remark: '--',
    inviteEmployeeId: 'EMP004',
    inviteEmployeeName: '周员工',
    groundPromotionQuestionnaire: '--',
    answer: '--',
    questionnaireSubmitTime: '0000-00-00 00:00:00',
    appointmentStore: '示例宝安店',
    isGiftTrialClass: '是',
    trialClassGetTime: '-',
    contractNo: '--',
    isAppointed: '是',
    trialClassStatus: '待上课',
    trialClassEndTime: '0000-00-00 00:00:00',
    userTags: '体验课意向',
    trialClassPayAmount: 199,
    trialClassConsultant: '李顾问',
    isRegistered: '否',
    repeatRetainCount: 0,
    latestRetainTime: '0000-00-00 00:00:00',
    invalidCustomerStatus: '--',
    createTime: '2026-07-05 11:00:00',
  },
  {
    key: '11',
    name: '黄强',
    firstAssignTime: '2026-07-11 14:00:00',
    lastAssignTime: '2026-07-18 10:00:00',
    isVisited: '已到店',
    isDeal: '未成交',
    appointmentTime: '2026-07-23 09:30:00',
    actualVisitStatus: '--',
    actualDealStatus: '--',
    id: 'SC011',
    userId: 'UID1011',
    wechatId: 'wx_huangqiang_11',
    phone: '139****1245',
    retainStore: '示例罗湖店',
    retainStoreRemark: '--',
    gender: '男',
    age: 36,
    source: '朋友推荐',
    customerType: '老客',
    isAssigned: '已分配',
    latestFollower: '孙主管',
    sharer: '赵员工',
    visitCount: 6,
    visitCount7d: 2,
    visitCount30d: 5,
    interviewCount: 3,
    interviewCount7d: 1,
    interviewCount30d: 2,
    conversionDays: 25,
    dealCycleDays: 40,
    latestEditor: '孙主管',
    remark: '有成交意向',
    inviteEmployeeId: 'EMP005',
    inviteEmployeeName: '钱员工',
    groundPromotionQuestionnaire: '--',
    answer: '--',
    questionnaireSubmitTime: '0000-00-00 00:00:00',
    appointmentStore: '示例罗湖店',
    isGiftTrialClass: '否',
    trialClassGetTime: '-',
    contractNo: 'HT2026002',
    isAppointed: '是',
    trialClassStatus: '--',
    trialClassEndTime: '0000-00-00 00:00:00',
    userTags: '意向客户,跟进中',
    trialClassPayAmount: '--',
    trialClassConsultant: '--',
    isRegistered: '是',
    repeatRetainCount: 2,
    latestRetainTime: '2026-07-11 14:00:00',
    invalidCustomerStatus: '--',
    createTime: '2026-07-04 08:00:00',
  },
  {
    key: '12',
    name: '杨静',
    firstAssignTime: '2026-07-10 12:00:00',
    lastAssignTime: '2026-07-17 16:00:00',
    isVisited: '--',
    isDeal: '--',
    appointmentTime: '-',
    actualVisitStatus: '--',
    actualDealStatus: '--',
    id: 'SC012',
    userId: 'UID1012',
    wechatId: 'wx_yangjing_12',
    phone: '138****6379',
    retainStore: '示例旗舰店',
    retainStoreRemark: '--',
    gender: '女',
    age: 24,
    source: '线上广告',
    customerType: '新客',
    isAssigned: '未分配',
    latestFollower: '--',
    sharer: '--',
    visitCount: 0,
    visitCount7d: 0,
    visitCount30d: 0,
    interviewCount: 0,
    interviewCount7d: 0,
    interviewCount30d: 0,
    conversionDays: '--',
    dealCycleDays: '--',
    latestEditor: '系统',
    remark: '--',
    inviteEmployeeId: '--',
    inviteEmployeeName: '--',
    groundPromotionQuestionnaire: '--',
    answer: '--',
    questionnaireSubmitTime: '0000-00-00 00:00:00',
    appointmentStore: '--',
    isGiftTrialClass: '否',
    trialClassGetTime: '-',
    contractNo: '--',
    isAppointed: '否',
    trialClassStatus: '--',
    trialClassEndTime: '0000-00-00 00:00:00',
    userTags: '--',
    trialClassPayAmount: '--',
    trialClassConsultant: '--',
    isRegistered: '否',
    repeatRetainCount: 0,
    latestRetainTime: '0000-00-00 00:00:00',
    invalidCustomerStatus: '--',
    createTime: '2026-07-03 15:00:00',
  },
  {
    key: '13',
    name: '何伟',
    firstAssignTime: '2026-07-09 10:00:00',
    lastAssignTime: '2026-07-16 13:00:00',
    isVisited: '已到店',
    isDeal: '未成交',
    appointmentTime: '2026-07-27 11:00:00',
    actualVisitStatus: '--',
    actualDealStatus: '--',
    id: 'SC013',
    userId: 'UID1013',
    wechatId: 'wx_hewei_13',
    phone: '137****5630',
    retainStore: '示例南山店',
    retainStoreRemark: '推荐亲子课程',
    gender: '男',
    age: 40,
    source: '会员推荐',
    customerType: '老客',
    isAssigned: '已分配',
    latestFollower: '赵主管',
    sharer: '--',
    visitCount: 9,
    visitCount7d: 3,
    visitCount30d: 7,
    interviewCount: 5,
    interviewCount7d: 1,
    interviewCount30d: 4,
    conversionDays: 35,
    dealCycleDays: 55,
    latestEditor: '赵主管',
    remark: '亲子课程意向',
    inviteEmployeeId: 'EMP002',
    inviteEmployeeName: '陈员工',
    groundPromotionQuestionnaire: '亲子课程意向',
    answer: '已填写',
    questionnaireSubmitTime: '2026-07-08 16:00:00',
    appointmentStore: '示例南山店',
    isGiftTrialClass: '是',
    trialClassGetTime: '2026-07-10 10:00:00',
    contractNo: '--',
    isAppointed: '是',
    trialClassStatus: '已下课',
    trialClassEndTime: '2026-07-13 18:00:00',
    userTags: '亲子,VIP',
    trialClassPayAmount: 499,
    trialClassConsultant: '张顾问',
    isRegistered: '是',
    repeatRetainCount: 4,
    latestRetainTime: '2026-07-09 10:00:00',
    invalidCustomerStatus: '--',
    createTime: '2026-07-01 09:00:00',
  },
  {
    key: '14',
    name: '林婷',
    firstAssignTime: '2026-07-08 13:30:00',
    lastAssignTime: '2026-07-15 11:30:00',
    isVisited: '未到店',
    isDeal: '未成交',
    appointmentTime: '2026-07-29 15:30:00',
    actualVisitStatus: '--',
    actualDealStatus: '--',
    id: 'SC014',
    userId: 'UID1014',
    wechatId: 'wx_linting_14',
    phone: '136****2984',
    retainStore: '示例福田店',
    retainStoreRemark: '--',
    gender: '女',
    age: 32,
    source: '商圈引流',
    customerType: '新客',
    isAssigned: '已分配',
    latestFollower: '张主管',
    sharer: '--',
    visitCount: 2,
    visitCount7d: 1,
    visitCount30d: 2,
    interviewCount: 1,
    interviewCount7d: 1,
    interviewCount30d: 1,
    conversionDays: '--',
    dealCycleDays: '--',
    latestEditor: '张主管',
    remark: '--',
    inviteEmployeeId: 'EMP003',
    inviteEmployeeName: '张员工',
    groundPromotionQuestionnaire: '--',
    answer: '--',
    questionnaireSubmitTime: '0000-00-00 00:00:00',
    appointmentStore: '示例福田店',
    isGiftTrialClass: '否',
    trialClassGetTime: '-',
    contractNo: '--',
    isAppointed: '是',
    trialClassStatus: '--',
    trialClassEndTime: '0000-00-00 00:00:00',
    userTags: '--',
    trialClassPayAmount: '--',
    trialClassConsultant: '--',
    isRegistered: '是',
    repeatRetainCount: 1,
    latestRetainTime: '2026-07-08 13:30:00',
    invalidCustomerStatus: '--',
    createTime: '2026-06-30 10:00:00',
  },
  {
    key: '15',
    name: '马超',
    firstAssignTime: '2026-07-07 09:00:00',
    lastAssignTime: '2026-07-14 15:00:00',
    isVisited: '已到店',
    isDeal: '--',
    appointmentTime: '-',
    actualVisitStatus: '--',
    actualDealStatus: '--',
    id: 'SC015',
    userId: 'UID1015',
    wechatId: 'wx_machao_15',
    phone: '135****7401',
    retainStore: '示例宝安店',
    retainStoreRemark: '--',
    gender: '男',
    age: 50,
    source: '朋友推荐',
    customerType: '新客',
    isAssigned: '已分配',
    latestFollower: '刘经理',
    sharer: '--',
    visitCount: 1,
    visitCount7d: 0,
    visitCount30d: 1,
    interviewCount: 0,
    interviewCount7d: 0,
    interviewCount30d: 0,
    conversionDays: '--',
    dealCycleDays: '--',
    latestEditor: '刘经理',
    remark: '--',
    inviteEmployeeId: 'EMP004',
    inviteEmployeeName: '周员工',
    groundPromotionQuestionnaire: '--',
    answer: '--',
    questionnaireSubmitTime: '0000-00-00 00:00:00',
    appointmentStore: '--',
    isGiftTrialClass: '否',
    trialClassGetTime: '-',
    contractNo: '--',
    isAppointed: '否',
    trialClassStatus: '--',
    trialClassEndTime: '0000-00-00 00:00:00',
    userTags: '--',
    trialClassPayAmount: '--',
    trialClassConsultant: '--',
    isRegistered: '否',
    repeatRetainCount: 0,
    latestRetainTime: '0000-00-00 00:00:00',
    invalidCustomerStatus: '--',
    createTime: '2026-06-29 14:00:00',
  },
  {
    key: '16',
    name: '韩雪',
    firstAssignTime: '2026-07-06 11:00:00',
    lastAssignTime: '2026-07-13 09:30:00',
    isVisited: '未到店',
    isDeal: '未成交',
    appointmentTime: '2026-07-31 13:00:00',
    actualVisitStatus: '--',
    actualDealStatus: '--',
    id: 'SC016',
    userId: 'UID1016',
    wechatId: 'wx_hanxue_16',
    phone: '134****1056',
    retainStore: '示例罗湖店',
    retainStoreRemark: '--',
    gender: '女',
    age: 26,
    source: '线上广告',
    customerType: '新客',
    isAssigned: '已分配',
    latestFollower: '孙主管',
    sharer: '--',
    visitCount: 4,
    visitCount7d: 2,
    visitCount30d: 4,
    interviewCount: 2,
    interviewCount7d: 0,
    interviewCount30d: 2,
    conversionDays: 12,
    dealCycleDays: '--',
    latestEditor: '孙主管',
    remark: '--',
    inviteEmployeeId: 'EMP005',
    inviteEmployeeName: '钱员工',
    groundPromotionQuestionnaire: '--',
    answer: '--',
    questionnaireSubmitTime: '0000-00-00 00:00:00',
    appointmentStore: '示例罗湖店',
    isGiftTrialClass: '否',
    trialClassGetTime: '-',
    contractNo: '--',
    isAppointed: '是',
    trialClassStatus: '--',
    trialClassEndTime: '0000-00-00 00:00:00',
    userTags: '意向客户',
    trialClassPayAmount: '--',
    trialClassConsultant: '--',
    isRegistered: '是',
    repeatRetainCount: 1,
    latestRetainTime: '2026-07-06 11:00:00',
    invalidCustomerStatus: '--',
    createTime: '2026-06-28 08:00:00',
  },
  {
    key: '17',
    name: '宋明',
    firstAssignTime: '2026-07-05 15:30:00',
    lastAssignTime: '2026-07-12 14:00:00',
    isVisited: '已到店',
    isDeal: '未成交',
    appointmentTime: '2026-07-24 10:00:00',
    actualVisitStatus: '--',
    actualDealStatus: '--',
    id: 'SC017',
    userId: 'UID1017',
    wechatId: 'wx_songming_17',
    phone: '133****4829',
    retainStore: '示例旗舰店',
    retainStoreRemark: '--',
    gender: '男',
    age: 34,
    source: '会员推荐',
    customerType: '老客',
    isAssigned: '已分配',
    latestFollower: '王经理',
    sharer: '陈员工',
    visitCount: 7,
    visitCount7d: 3,
    visitCount30d: 6,
    interviewCount: 4,
    interviewCount7d: 2,
    interviewCount30d: 3,
    conversionDays: 18,
    dealCycleDays: 30,
    latestEditor: '王经理',
    remark: '跟进中',
    inviteEmployeeId: 'EMP001',
    inviteEmployeeName: '李员工',
    groundPromotionQuestionnaire: '--',
    answer: '--',
    questionnaireSubmitTime: '0000-00-00 00:00:00',
    appointmentStore: '示例旗舰店',
    isGiftTrialClass: '是',
    trialClassGetTime: '2026-07-06 11:00:00',
    contractNo: 'HT2026003',
    isAppointed: '是',
    trialClassStatus: '已下课',
    trialClassEndTime: '2026-07-09 17:00:00',
    userTags: '老客推荐',
    trialClassPayAmount: 299,
    trialClassConsultant: '王顾问',
    isRegistered: '是',
    repeatRetainCount: 3,
    latestRetainTime: '2026-07-05 15:30:00',
    invalidCustomerStatus: '--',
    createTime: '2026-06-27 10:00:00',
  },
  {
    key: '18',
    name: '高源',
    firstAssignTime: '2026-07-04 08:30:00',
    lastAssignTime: '2026-07-11 16:30:00',
    isVisited: '--',
    isDeal: '--',
    appointmentTime: '-',
    actualVisitStatus: '--',
    actualDealStatus: '--',
    id: 'SC018',
    userId: 'UID1018',
    wechatId: 'wx_gaoyuan_18',
    phone: '132****6371',
    retainStore: '示例南山店',
    retainStoreRemark: '--',
    gender: '男',
    age: 30,
    source: '地推活动',
    customerType: '新客',
    isAssigned: '未分配',
    latestFollower: '--',
    sharer: '--',
    visitCount: 0,
    visitCount7d: 0,
    visitCount30d: 0,
    interviewCount: 0,
    interviewCount7d: 0,
    interviewCount30d: 0,
    conversionDays: '--',
    dealCycleDays: '--',
    latestEditor: '系统',
    remark: '--',
    inviteEmployeeId: '--',
    inviteEmployeeName: '--',
    groundPromotionQuestionnaire: '--',
    answer: '--',
    questionnaireSubmitTime: '0000-00-00 00:00:00',
    appointmentStore: '--',
    isGiftTrialClass: '否',
    trialClassGetTime: '-',
    contractNo: '--',
    isAppointed: '否',
    trialClassStatus: '--',
    trialClassEndTime: '0000-00-00 00:00:00',
    userTags: '--',
    trialClassPayAmount: '--',
    trialClassConsultant: '--',
    isRegistered: '否',
    repeatRetainCount: 0,
    latestRetainTime: '0000-00-00 00:00:00',
    invalidCustomerStatus: '--',
    createTime: '2026-06-26 13:00:00',
  },
  {
    key: '19',
    name: '唐雯',
    firstAssignTime: '2026-07-03 14:00:00',
    lastAssignTime: '2026-07-10 10:00:00',
    isVisited: '未到店',
    isDeal: '未成交',
    appointmentTime: '2026-08-02 16:00:00',
    actualVisitStatus: '--',
    actualDealStatus: '--',
    id: 'SC019',
    userId: 'UID1019',
    wechatId: 'wx_tangwen_19',
    phone: '131****9045',
    retainStore: '示例福田店',
    retainStoreRemark: '需要更多课程信息',
    gender: '女',
    age: 37,
    source: '线上广告',
    customerType: '新客',
    isAssigned: '已分配',
    latestFollower: '张主管',
    sharer: '--',
    visitCount: 3,
    visitCount7d: 1,
    visitCount30d: 3,
    interviewCount: 1,
    interviewCount7d: 0,
    interviewCount30d: 1,
    conversionDays: '--',
    dealCycleDays: '--',
    latestEditor: '张主管',
    remark: '--',
    inviteEmployeeId: 'EMP003',
    inviteEmployeeName: '张员工',
    groundPromotionQuestionnaire: '课程咨询',
    answer: '已填写',
    questionnaireSubmitTime: '2026-07-02 15:00:00',
    appointmentStore: '示例福田店',
    isGiftTrialClass: '是',
    trialClassGetTime: '-',
    contractNo: '--',
    isAppointed: '是',
    trialClassStatus: '待上课',
    trialClassEndTime: '0000-00-00 00:00:00',
    userTags: '课程咨询',
    trialClassPayAmount: 199,
    trialClassConsultant: '张顾问',
    isRegistered: '否',
    repeatRetainCount: 0,
    latestRetainTime: '0000-00-00 00:00:00',
    invalidCustomerStatus: '--',
    createTime: '2026-06-25 09:00:00',
  },
  {
    key: '20',
    name: '罗毅',
    firstAssignTime: '2026-07-02 10:30:00',
    lastAssignTime: '2026-07-09 13:00:00',
    isVisited: '已到店',
    isDeal: '--',
    appointmentTime: '2026-07-28 14:00:00',
    actualVisitStatus: '--',
    actualDealStatus: '--',
    id: 'SC020',
    userId: 'UID1020',
    wechatId: 'wx_luoyi_20',
    phone: '130****2178',
    retainStore: '示例宝安店',
    retainStoreRemark: '--',
    gender: '男',
    age: 43,
    source: '商圈引流',
    customerType: '老客',
    isAssigned: '已分配',
    latestFollower: '刘经理',
    sharer: '赵员工',
    visitCount: 10,
    visitCount7d: 3,
    visitCount30d: 8,
    interviewCount: 5,
    interviewCount7d: 2,
    interviewCount30d: 5,
    conversionDays: 28,
    dealCycleDays: 50,
    latestEditor: '刘经理',
    remark: '老客户续费意向',
    inviteEmployeeId: 'EMP004',
    inviteEmployeeName: '周员工',
    groundPromotionQuestionnaire: '--',
    answer: '--',
    questionnaireSubmitTime: '0000-00-00 00:00:00',
    appointmentStore: '示例宝安店',
    isGiftTrialClass: '否',
    trialClassGetTime: '-',
    contractNo: 'HT2026004',
    isAppointed: '是',
    trialClassStatus: '--',
    trialClassEndTime: '0000-00-00 00:00:00',
    userTags: '续费意向',
    trialClassPayAmount: '--',
    trialClassConsultant: '--',
    isRegistered: '是',
    repeatRetainCount: 6,
    latestRetainTime: '2026-07-02 10:30:00',
    invalidCustomerStatus: '--',
    createTime: '2026-06-24 11:00:00',
  },
  {
    key: '21',
    name: '许晗',
    firstAssignTime: '2026-07-01 09:00:00',
    lastAssignTime: '2026-07-08 15:00:00',
    isVisited: '未到店',
    isDeal: '未成交',
    appointmentTime: '-',
    actualVisitStatus: '--',
    actualDealStatus: '--',
    id: 'SC021',
    userId: 'UID1021',
    wechatId: 'wx_xuhan_21',
    phone: '139****3509',
    retainStore: '示例罗湖店',
    retainStoreRemark: '--',
    gender: '女',
    age: 23,
    source: '朋友推荐',
    customerType: '新客',
    isAssigned: '已分配',
    latestFollower: '孙主管',
    sharer: '--',
    visitCount: 0,
    visitCount7d: 0,
    visitCount30d: 0,
    interviewCount: 0,
    interviewCount7d: 0,
    interviewCount30d: 0,
    conversionDays: '--',
    dealCycleDays: '--',
    latestEditor: '孙主管',
    remark: '--',
    inviteEmployeeId: 'EMP005',
    inviteEmployeeName: '钱员工',
    groundPromotionQuestionnaire: '--',
    answer: '--',
    questionnaireSubmitTime: '0000-00-00 00:00:00',
    appointmentStore: '--',
    isGiftTrialClass: '否',
    trialClassGetTime: '-',
    contractNo: '--',
    isAppointed: '否',
    trialClassStatus: '--',
    trialClassEndTime: '0000-00-00 00:00:00',
    userTags: '--',
    trialClassPayAmount: '--',
    trialClassConsultant: '--',
    isRegistered: '否',
    repeatRetainCount: 0,
    latestRetainTime: '0000-00-00 00:00:00',
    invalidCustomerStatus: '--',
    createTime: '2026-06-23 16:00:00',
  },
  {
    key: '22',
    name: '沈鹏',
    firstAssignTime: '2026-06-30 14:00:00',
    lastAssignTime: '2026-07-07 11:00:00',
    isVisited: '已到店',
    isDeal: '--',
    appointmentTime: '2026-07-26 09:30:00',
    actualVisitStatus: '--',
    actualDealStatus: '--',
    id: 'SC022',
    userId: 'UID1022',
    wechatId: 'wx_shenpeng_22',
    phone: '138****7612',
    retainStore: '示例旗舰店',
    retainStoreRemark: '--',
    gender: '男',
    age: 47,
    source: '会员推荐',
    customerType: '老客',
    isAssigned: '已分配',
    latestFollower: '王经理',
    sharer: '--',
    visitCount: 15,
    visitCount7d: 5,
    visitCount30d: 12,
    interviewCount: 8,
    interviewCount7d: 3,
    interviewCount30d: 6,
    conversionDays: 40,
    dealCycleDays: 90,
    latestEditor: '王经理',
    remark: 'VIP客户维护',
    inviteEmployeeId: 'EMP001',
    inviteEmployeeName: '李员工',
    groundPromotionQuestionnaire: '--',
    answer: '--',
    questionnaireSubmitTime: '0000-00-00 00:00:00',
    appointmentStore: '示例旗舰店',
    isGiftTrialClass: '是',
    trialClassGetTime: '2026-07-01 10:00:00',
    contractNo: 'HT2026005',
    isAppointed: '是',
    trialClassStatus: '已下课',
    trialClassEndTime: '2026-07-04 18:00:00',
    userTags: 'VIP,高意向',
    trialClassPayAmount: 599,
    trialClassConsultant: '王顾问',
    isRegistered: '是',
    repeatRetainCount: 8,
    latestRetainTime: '2026-06-30 14:00:00',
    invalidCustomerStatus: '--',
    createTime: '2026-06-22 10:00:00',
  },
  {
    key: '23',
    name: '秦悦',
    firstAssignTime: '2026-06-29 11:00:00',
    lastAssignTime: '2026-07-06 10:00:00',
    isVisited: '已到店',
    isDeal: '未成交',
    appointmentTime: '2026-07-25 15:30:00',
    actualVisitStatus: '--',
    actualDealStatus: '--',
    id: 'SC023',
    userId: 'UID1023',
    wechatId: 'wx_qinyue_23',
    phone: '137****4193',
    retainStore: '示例南山店',
    retainStoreRemark: '--',
    gender: '女',
    age: 39,
    source: '地推活动',
    customerType: '新客',
    isAssigned: '已分配',
    latestFollower: '赵主管',
    sharer: '--',
    visitCount: 5,
    visitCount7d: 2,
    visitCount30d: 4,
    interviewCount: 2,
    interviewCount7d: 1,
    interviewCount30d: 2,
    conversionDays: 22,
    dealCycleDays: '--',
    latestEditor: '赵主管',
    remark: '--',
    inviteEmployeeId: 'EMP002',
    inviteEmployeeName: '陈员工',
    groundPromotionQuestionnaire: '--',
    answer: '--',
    questionnaireSubmitTime: '0000-00-00 00:00:00',
    appointmentStore: '示例南山店',
    isGiftTrialClass: '否',
    trialClassGetTime: '-',
    contractNo: '--',
    isAppointed: '是',
    trialClassStatus: '--',
    trialClassEndTime: '0000-00-00 00:00:00',
    userTags: '--',
    trialClassPayAmount: '--',
    trialClassConsultant: '--',
    isRegistered: '否',
    repeatRetainCount: 0,
    latestRetainTime: '0000-00-00 00:00:00',
    invalidCustomerStatus: '--',
    createTime: '2026-06-21 09:00:00',
  },
  {
    key: '24',
    name: '方浩',
    firstAssignTime: '2026-06-28 08:00:00',
    lastAssignTime: '2026-07-05 14:00:00',
    isVisited: '--',
    isDeal: '--',
    appointmentTime: '-',
    actualVisitStatus: '--',
    actualDealStatus: '--',
    id: 'SC024',
    userId: 'UID1024',
    wechatId: 'wx_fanghao_24',
    phone: '136****8305',
    retainStore: '示例福田店',
    retainStoreRemark: '--',
    gender: '男',
    age: 52,
    source: '商圈引流',
    customerType: '新客',
    isAssigned: '未分配',
    latestFollower: '--',
    sharer: '--',
    visitCount: 0,
    visitCount7d: 0,
    visitCount30d: 0,
    interviewCount: 0,
    interviewCount7d: 0,
    interviewCount30d: 0,
    conversionDays: '--',
    dealCycleDays: '--',
    latestEditor: '系统',
    remark: '--',
    inviteEmployeeId: '--',
    inviteEmployeeName: '--',
    groundPromotionQuestionnaire: '--',
    answer: '--',
    questionnaireSubmitTime: '0000-00-00 00:00:00',
    appointmentStore: '--',
    isGiftTrialClass: '否',
    trialClassGetTime: '-',
    contractNo: '--',
    isAppointed: '否',
    trialClassStatus: '--',
    trialClassEndTime: '0000-00-00 00:00:00',
    userTags: '--',
    trialClassPayAmount: '--',
    trialClassConsultant: '--',
    isRegistered: '否',
    repeatRetainCount: 0,
    latestRetainTime: '0000-00-00 00:00:00',
    invalidCustomerStatus: '--',
    createTime: '2026-06-20 08:30:00',
  },
  {
    key: '25',
    name: '袁瑶',
    firstAssignTime: '2026-06-27 15:00:00',
    lastAssignTime: '2026-07-04 12:00:00',
    isVisited: '未到店',
    isDeal: '未成交',
    appointmentTime: '2026-08-03 10:00:00',
    actualVisitStatus: '--',
    actualDealStatus: '--',
    id: 'SC025',
    userId: 'UID1025',
    wechatId: 'wx_yuanyao_25',
    phone: '135****1574',
    retainStore: '示例宝安店',
    retainStoreRemark: '关注成人课程',
    gender: '女',
    age: 41,
    source: '线上广告',
    customerType: '老客',
    isAssigned: '已分配',
    latestFollower: '刘经理',
    sharer: '--',
    visitCount: 4,
    visitCount7d: 1,
    visitCount30d: 3,
    interviewCount: 2,
    interviewCount7d: 0,
    interviewCount30d: 2,
    conversionDays: 16,
    dealCycleDays: 35,
    latestEditor: '刘经理',
    remark: '成人课程咨询',
    inviteEmployeeId: 'EMP004',
    inviteEmployeeName: '周员工',
    groundPromotionQuestionnaire: '成人课程意向',
    answer: '已提交',
    questionnaireSubmitTime: '2026-06-26 14:00:00',
    appointmentStore: '示例宝安店',
    isGiftTrialClass: '是',
    trialClassGetTime: '-',
    contractNo: '--',
    isAppointed: '是',
    trialClassStatus: '待上课',
    trialClassEndTime: '0000-00-00 00:00:00',
    userTags: '成人课程',
    trialClassPayAmount: 299,
    trialClassConsultant: '李顾问',
    isRegistered: '是',
    repeatRetainCount: 2,
    latestRetainTime: '2026-06-27 15:00:00',
    invalidCustomerStatus: '--',
    createTime: '2026-06-19 13:00:00',
  },
];

export default rawCustomers;
