/**
 * 0012 Cycle A - 到店记录业务模块 Mock 数据与选择器。
 *
 * 独立页（到店记录）读取全部记录；跟进详情"到店记录"Tab 按稳定客户 key
 * 读取当前客户记录。两个入口共用同一份初始数据源，禁止复制两套数组。
 *
 * 0011 迁移：张三（key '1'）三条到店记录原样迁入，保证跟进详情既有断言
 * 与 Story 数据不变；另补充陈晨（key '5'）、赵敏（key '6'）演示数据，
 * 用于独立页正常列表与筛选演示（不触碰李四 key '2' 的空态断言）。
 * 所有数据均为虚构演示数据。
 */
import type { ArrivalRecord } from './arrivalRecordTypes';

const ARRIVAL_RECORDS_BY_CUSTOMER: Record<string, ArrivalRecord[]> = {
  '1': [
    {
      key: 'a1',
      customerKey: '1',
      id: 'AR001',
      userName: '张三',
      userId: 'UID1001',
      wechatId: 'wx_zhangsan_01',
      phone: '139****4822',
      source: '地推活动',
      appointmentStore: '示例旗舰店',
      arrivalTime: '2026-07-22 17:00:00',
      isArrived: '已到店',
      isDeal: '已成交',
      dealAmount: 299.9,
      courseType: '少儿体适能',
      hasTrialClass: '是',
      trialClassStatus: '已下课',
      isSignedIn: '已签到',
      trialClassCoach: '张顾问',
      trialClassEndTime: '2026-07-22 18:00:00',
      contractNo: 'HT2026001',
      trialClassCardContractStatus: '已生效',
      trialClassCard: '体验课A卡',
      actualPaidAmount: 199,
      trialClassGetTime: '2026-07-20 10:00:00',
      intentLevel: 5,
      improvementNeed: '改善基础体能',
      intendedCourse: '少儿体适能课',
      appointmentRemark: '--',
      resultAnalysis: '到店体验良好，家长有明确报名意向',
      creator: '王经理',
      createTime: '2026-07-18 09:00:00',
      updater: '王经理',
      updateTime: '2026-07-22 18:00:00',
    },
    {
      key: 'a2',
      customerKey: '1',
      id: 'AR002',
      userName: '张三',
      userId: 'UID1001',
      wechatId: 'wx_zhangsan_01',
      phone: '139****4822',
      source: '地推活动',
      appointmentStore: '示例旗舰店',
      arrivalTime: '2026-07-20 14:30:00',
      isArrived: '已到店',
      isDeal: '未成交',
      dealAmount: 0,
      courseType: '儿童篮球',
      hasTrialClass: '是',
      trialClassStatus: '待上课',
      isSignedIn: '已签到',
      trialClassCoach: '李教练',
      trialClassEndTime: '--',
      contractNo: '--',
      trialClassCardContractStatus: '待生效',
      trialClassCard: '体验课B卡',
      actualPaidAmount: 0,
      trialClassGetTime: '2026-07-20 10:00:00',
      intentLevel: 3,
      improvementNeed: '提升身体协调能力',
      intendedCourse: '儿童篮球课',
      appointmentRemark: '家长咨询课程方案',
      resultAnalysis: '意向较高，待持续跟进',
      creator: '王经理',
      createTime: '2026-07-19 10:00:00',
      updater: '王经理',
      updateTime: '2026-07-20 15:00:00',
    },
    {
      key: 'a3',
      customerKey: '1',
      id: 'AR003',
      userName: '张三',
      userId: 'UID1001',
      wechatId: 'wx_zhangsan_01',
      phone: '139****4822',
      source: '地推活动',
      appointmentStore: '示例旗舰店',
      arrivalTime: '2026-07-18 10:00:00',
      isArrived: '未到店',
      isDeal: '未成交',
      dealAmount: null,
      courseType: '亲子运动',
      hasTrialClass: '否',
      trialClassStatus: '--',
      isSignedIn: '--',
      trialClassCoach: '--',
      trialClassEndTime: '--',
      contractNo: '--',
      trialClassCardContractStatus: '--',
      trialClassCard: '--',
      actualPaidAmount: null,
      trialClassGetTime: '--',
      intentLevel: 2,
      improvementNeed: '改善亲子互动',
      intendedCourse: '亲子运动课',
      appointmentRemark: '--',
      resultAnalysis: '临时有事未到店，改约下次',
      creator: '王经理',
      createTime: '2026-07-16 14:00:00',
      updater: '王经理',
      updateTime: '2026-07-18 11:00:00',
    },
  ],
  '5': [
    {
      key: 'a4',
      customerKey: '5',
      id: 'AR004',
      userName: '陈晨',
      userId: 'UID1005',
      wechatId: 'wx_chenchen_05',
      phone: '135****3507',
      source: '线上广告',
      appointmentStore: '示例宝安店',
      arrivalTime: '2026-07-19 15:00:00',
      isArrived: '已到店',
      isDeal: '已成交',
      dealAmount: 499,
      courseType: '成人瑜伽',
      hasTrialClass: '是',
      trialClassStatus: '已下课',
      isSignedIn: '已签到',
      trialClassCoach: '李教练',
      trialClassEndTime: '2026-07-19 16:00:00',
      contractNo: 'HT2026004',
      trialClassCardContractStatus: '已生效',
      trialClassCard: '体验课C卡',
      actualPaidAmount: 499,
      trialClassGetTime: '2026-07-18 10:00:00',
      intentLevel: 4,
      improvementNeed: '体态调整',
      intendedCourse: '精品私教',
      appointmentRemark: '--',
      resultAnalysis: '体验良好，当天下单',
      creator: '李顾问',
      createTime: '2026-07-18 11:00:00',
      updater: '李顾问',
      updateTime: '2026-07-19 16:00:00',
    },
  ],
  '6': [
    {
      key: 'a5',
      customerKey: '6',
      id: 'AR005',
      userName: '赵敏',
      userId: 'UID1006',
      wechatId: 'wx_zhaomin_06',
      phone: '134****6284',
      source: '朋友推荐',
      appointmentStore: '示例罗湖店',
      arrivalTime: '2026-07-21 10:30:00',
      isArrived: '未到店',
      isDeal: '未成交',
      dealAmount: null,
      courseType: '亲子运动',
      hasTrialClass: '否',
      trialClassStatus: '--',
      isSignedIn: '--',
      trialClassCoach: '--',
      trialClassEndTime: '--',
      contractNo: '--',
      trialClassCardContractStatus: '--',
      trialClassCard: '--',
      actualPaidAmount: null,
      trialClassGetTime: '--',
      intentLevel: 2,
      improvementNeed: '改善亲子互动',
      intendedCourse: '亲子运动课',
      appointmentRemark: '--',
      resultAnalysis: '临时有事未到店',
      creator: '王经理',
      createTime: '2026-07-20 14:00:00',
      updater: '王经理',
      updateTime: '2026-07-21 10:30:00',
    },
    {
      key: 'a6',
      customerKey: '6',
      id: 'AR006',
      userName: '赵敏',
      userId: 'UID1006',
      wechatId: 'wx_zhaomin_06',
      phone: '134****6284',
      source: '朋友推荐',
      appointmentStore: '示例罗湖店',
      arrivalTime: '2026-07-16 09:30:00',
      isArrived: '已到店',
      isDeal: '未成交',
      dealAmount: 0,
      courseType: '成人瑜伽',
      hasTrialClass: '是',
      trialClassStatus: '已下课',
      isSignedIn: '已签到',
      trialClassCoach: '李教练',
      trialClassEndTime: '2026-07-16 10:30:00',
      contractNo: '--',
      trialClassCardContractStatus: '已生效',
      trialClassCard: '体验课C卡',
      actualPaidAmount: 0,
      trialClassGetTime: '2026-07-15 16:00:00',
      intentLevel: 3,
      improvementNeed: '体态调整',
      intendedCourse: '成人瑜伽课',
      appointmentRemark: '--',
      resultAnalysis: '首次到店体验，意向待确认',
      creator: '李顾问',
      createTime: '2026-07-15 17:00:00',
      updater: '李顾问',
      updateTime: '2026-07-16 10:30:00',
    },
    {
      key: 'a7',
      customerKey: '6',
      id: 'AR007',
      userName: '赵敏',
      userId: 'UID1006',
      wechatId: 'wx_zhaomin_06',
      phone: '134****6284',
      source: '朋友推荐',
      appointmentStore: '示例罗湖店',
      arrivalTime: '2026-07-14 14:00:00',
      isArrived: '已到店',
      isDeal: '未成交',
      dealAmount: 0,
      courseType: '成人瑜伽',
      hasTrialClass: '是',
      trialClassStatus: '已下课',
      isSignedIn: '已签到',
      trialClassCoach: '李教练',
      trialClassEndTime: '2026-07-14 15:00:00',
      contractNo: '--',
      trialClassCardContractStatus: '待生效',
      trialClassCard: '体验课C卡',
      actualPaidAmount: 0,
      trialClassGetTime: '2026-07-13 16:00:00',
      intentLevel: 3,
      improvementNeed: '体态调整',
      intendedCourse: '成人瑜伽课',
      appointmentRemark: '--',
      resultAnalysis: '',
      creator: '李顾问',
      createTime: '2026-07-13 17:00:00',
      updater: '李顾问',
      updateTime: '2026-07-14 15:00:00',
    },
  ],
};

/** 独立页到店记录数据源：全部记录（按客户 key 定义的稳定顺序）。 */
export function getAllArrivalRecords(): ArrivalRecord[] {
  return Object.values(ARRIVAL_RECORDS_BY_CUSTOMER).flat();
}

/** 跟进详情"到店记录"Tab 数据源：按稳定客户 key 读取当前客户记录。 */
export function getArrivalRecordsByCustomerKey(customerKey: string): ArrivalRecord[] {
  return ARRIVAL_RECORDS_BY_CUSTOMER[customerKey] ?? [];
}
